spring:
  data:
    mongodb:
      uri: mongodb://localhost
      database: chatchit
      port: 27017

  # SECURITY
  security:
    oauth2:
       client:
         registration:
           google:
             client-id: 123
             client-secret: 123
  # Server mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dduymen@gmail.com
    password: vcuwqngagorsvitw
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090

app:
  baseURL: localhost:8080
  name: ChatChit
  jwt:
    secretKey: c3ckfrhaKW8Mplm9ylgQCsMLoFmsip/ouP1u51eWRLRtCgDA6OFoLH+azJtNEDUYODPqhm/Kms2jYJdaIczcrap9vBVrbd7qMk1AuoNJjZg=
    expiration-time-ms: 86400000 # 30 minutes
  token:
    refresh:
      expiration-time-ms: 86400000 # a day

    registration:
      expiration-time-ms: 900000 # 15 minutes
      verify-endpoint: ${url.domain}/api/v1/auth/verify-registration

    forgot-password:
      expiration-time-ms: 1800000 # 30 minutes
      verify-endpoint: ${url.domain}/api/v1/auth/verify-forgot-password
