spring:
  data:
    mongodb:
      uri: mongodb+srv://menesforenglish102:V6vvtqJ4VHgWM6Ba@cluster0.dnahmhf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: chatchit
      port: 27017


  # SECURITY
  security:
    oauth2:
       client:
         registration:
           google:
             client-id: 123
             client-secret: 123
  # Server mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dduymen@gmail.com
    password: vcuwqngagorsvitw
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090

# SWAGGER - http://localhost:9090/swagger-ui/index.html
open-api:
  service:
    api-docs: API documentss
    title: Chat-API
    version: v1.0.0
    server: http://localhost:9090

app:
  baseURL: http://localhost:${server.port}
  name: ChatChit
  jwt:
    secretKey: c3ckfrhaKW8Mplm9ylgQCsMLoFmsip/ouP1u51eWRLRtCgDA6OFoLH+azJtNEDUYODPqhm/Kms2jYJdaIczcrap9vBVrbd7qMk1AuoNJjZg=
    expiration-time-ms: 86400000 # 30 minutes
  token:
    refresh:
      expiration-time-ms: 86400000 # a day
    registration:
      expiration-time-ms: 900000 # 15 minutes
    forgot-password:
      expiration-time-ms: 1800000 # 30 minutes
    reset-password:
      expiration-time-ms: 1800000 # 30 minutes


  endpoint:
    security:
      verify-new-user: ${app.baseURL}/api/v1/auth/verify-new-user
      reset-password: ${app.baseURL}/api/v1/auth/reset-password






