spring:
  data:
    mongodb:
      uri: mongodb+srv://20130072:PweEnQ86H5y5pRZp@websocket.zvdnie0.mongodb.net/?retryWrites=true&w=majority&appName=websocket
      username: 20130072
      password: PweEnQ86H5y5pRZp
      database: websocket
      port: 27017
      authentication-database: admin

  # SECURITY
  security:
    oauth2:
       client:
         registration:
           google:
             client-id: ###
             client-secret: ##
  # Server mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dduymen@gmail.com
    password: vcuwqngagorsvitw
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090